apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pet
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: helm/petclinic
    repoURL: https://github.com/nitheesh500/argocd-helm-cd.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      enabled: true
